### ISSUE TITLE
Tools don't appear correctly on player shadows in first person

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#144]
### Bug Description
When you are in first person, your own players shadow shows:
- The hammer in the wrong position and not animating
- The wrench is completely missing
- The printer in the wrong position

### Screenshots
https://github.com/ClayHanson/Blockland-Rebuilt-BetaTesters/assets/25954813/e927b90a-9575-4bd7-84b9-77bfbfc8a91e

### Metadata:
 - Game Version: `v0.18`

**Comment by consoleSkunk** [comment]
![Screenshot_2023-07-25_13-37-11](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/50500602/f33cf039-fb4f-497d-9a76-8bda2f94dd6b)

The wrench is visible in player shadows if you have the cop hat equipped.

Edit: Additionally, item shadows appear to be based on the first person model location rather than third person.

**Comment by consoleSkunk** [comment]
This appears to be fixed as of `v1.5-rev1904`.
