### ISSUE TITLE
guiHealthbarCtrl can show health

### ISSUE THREAD

**Issue by maxymax13** [ClayHanson/BlocklandRebuilt-IssueBoard#333]
### Bug Description
the "showEnergy" member field of guiHealthbarCtrl works here and lets you see your health, in retail this field is dummied out and bars always show energy instead

### Screenshots
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/38844529/feccafd0-0252-4d85-9c20-5d9ca16e27e8)

### Metadata:
 - Game Version: `v1.2`

### Additional context
in retail it was still possible to see you and others' health with things like BLHack, would it be possible to disable health being networked to clients entirely/make it always the same value? or would that break everything somehow

**Comment by Elletra** [comment]
I don't know if we need to break features just so we have parity with Blockland... It would be nice to have an ability to show a client's health without a bottom print loop. Maybe a `showHealthToClient` field or something? (Maybe on `Player` instead of `PlayerData` cause I think it'd be annoying to have it be a datablock field)
