### ISSUE TITLE
Vehicle third-person camera is sometimes not positioned correctly

### ISSUE THREAD

**Issue by Kenkoman** [ClayHanson/BlocklandRebuilt-IssueBoard#391]
### Bug Description
On some specific vehicles, the third person camera is positioned quite incorrectly.
Observed on:
- Vehicle_NewSpeedkart (used on my speedkart server)
- Vehicle_Racing_Kart (unusable in rebuilt)

### Screenshots
Speedkart Blocko in Retail: 
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/8bc47c5d-bf7b-47b0-b122-16c16dca47e9)
Speedkart Blocko in Rebuilt:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/0ca4a818-7078-491d-8884-1d274f0e9169)
Racing Kart in Retail:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/90abd46c-bd99-4d30-9d61-5ab5c0c77d73)
Racing Kart in Rebuilt:
![image](https://github.com/ClayHanson/BlocklandRebuilt-IssueBoard/assets/25954813/04c791e6-21c1-4cac-a83a-7e71a49f1dc9)

### Metadata:
 - Game Version: `v2.6`

### Additional context
People have reported this also happening with some of Filipe1020s more recent vehicle add-ons

**Comment by ClayHanson** [comment]
I am unable to find Vehicle_Racing_Kart. Additionally, I need specific vehicle names from BOTH of these vehicles so I can fix this faster.

**Comment by ClayHanson** [comment]
This is an issue that I do not know how to fix legitimately, because there is no discernable reason that this vehicle's camera should be treated any differently than other vehicles' cameras, but for some damn reason the camera offset is multiplied by 2. Maybe its bad code, or maybe its God himself that does that; I really don't know. I'm just going to add a hard fix for this vehicle until somebody can tell me what's going on.

**Comment by Kenkoman** [comment]
This current solution is a bodge-fix for specific vehicles - if anyone finds any more vehicles with offset cameras, please reopen this issue and report them (exact addon zip is appreciated, either linked or uploaded)
